name: Build turnertime Advent of Code 2020

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Install dependencies
        run: dotnet restore
      - name: Install tools
        run: dotnet tool restore
      - name: Check formatting
        run: dotnet format --check
      - name: Build
        run: dotnet build --configuration Release --no-restore
